info:
  build:
    artifact: @project.artifactId@
    description : @project.description@
    version : @project.version@

server:
  port: 8080
  address: 127.0.0.1


spring:
  data:
    rest:
      basePath: /api

security:
  user:
    password: test
  filter-order: 1

logging:
  level:
    org.springframework.security: DEBUG